version: '3.7'
services:
  database:
    image: postgres
    hostname: postgresdb
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: postgres-container

# Using start:dev while development
#  server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: .env
#    depends_on:
#      - database
#    networks:
#      - default
#    ports:
#      - '8080:8080'
#    container_name: wishlistr-server-container

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - database
    ports:
      - '5555:80'
    env_file: .env
    restart: unless-stopped
    container_name: pgadmin-container

volumes:
  postgres-data:
